- name: Installation d'un serveur apache et d'un projet gatsby

  hosts: vagrant

  become: true

  tasks:

  - name: Récupérer les facts et les stocker dans une variable    
    ansible.builtin.debug:
      var: ansible_facts

  - name: Installation du serveur apache sur OS amazon
    yum:
      name: httpd
      state: present
    when: ansible_facts['os_family'] | lower == 'amazon'

  - name: Installation du serveur apache sur OS debian
    apt:
      name: apache2
      state: present
    when: ansible_facts['os_family'] | lower == 'debian'

  - name: Copie du projet gatsby
    copy:
      src: ../ressources/projet-gatsby/public/
      dest: /var/www/html/
      
  - name: Démarrage du serveur apache sur OS amazon
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_facts['os_family'] | lower == 'amazon'

  - name: Démarage du serveur apache sur OS debian
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_facts['os_family'] | lower == 'debian'