- name: Installation de gatsby-cli

  hosts: ec2

  become: true

  tasks:

  - name: Récupérer les facts et les stocker dans une variable    
    ansible.builtin.debug:
      var: ansible_facts

  - name: Installer les paquets pour la compilation de Node.js
    ansible.builtin.yum:
      name:      
        - gcc-c++
        - make      
      state: present

  - name: Installer Node.js
    ansible.builtin.yum:
      name: nodejs
      state: present
      enablerepo: epel
  
  - name: Installer gatsby-cli
    ansible.builtin.npm:
      name: gatsby-cli
      global: yes
  
  