---
- name: Installation de gatsby-cli
  hosts: ec2
  become: true
  tasks:
    - name: Récupérer les facts et les stocker dans une variable    
      debug:
        var: ansible_facts

    - name: Variables de paquets pour OS 'redhat'
      set_fact:
        redhat_packages:
          - gcc-c++
          - make
          - nodejs

    - name: Variables de paquets pour OS 'debian'
      set_fact:
        debian_packages:
          - g++
          - make
          - nodejs         

    - name: Mettre à jour le gestionnaire de paquets sur OS 'debian'
      apt:
        update_cache: yes 
      when: ansible_facts['os_family'] | lower == 'debian'

    - name: "Add nodejs apt key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      when: ansible_facts['os_family'] | lower == 'debian'

    - name: "Add nodejs 18.x ppa for apt repo"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_18.x bionic main
        update_cache: yes 
      when: ansible_facts['os_family'] | lower == 'debian'

    - name: Installer les paquets pour de compilation, nodejs et npm sur OS 'redhat'
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ redhat_packages }}"
      when: ansible_facts['os_family'] | lower == 'redhat'

    - name: Installer les paquets de compilation, nodejs et npm sur OS 'debian'
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ debian_packages }}"
      when: ansible_facts['os_family'] | lower == 'debian'

    - name: Installer gatsby-cli
      npm:
        name: gatsby-cli
        global: yes
